export default {
  login: 'MunrraMT',
  id: 54816857,
  node_id: 'MDQ6VXNlcjU0ODE2ODU3',
  avatar_url: 'https://avatars.githubusercontent.com/u/54816857?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/MunrraMT',
  html_url: 'https://github.com/MunrraMT',
  followers_url: 'https://api.github.com/users/MunrraMT/followers',
  following_url: 'https://api.github.com/users/MunrraMT/following{/other_user}',
  gists_url: 'https://api.github.com/users/MunrraMT/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/MunrraMT/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/MunrraMT/subscriptions',
  organizations_url: 'https://api.github.com/users/MunrraMT/orgs',
  repos_url: 'https://api.github.com/users/MunrraMT/repos',
  events_url: 'https://api.github.com/users/MunrraMT/events{/privacy}',
  received_events_url: 'https://api.github.com/users/MunrraMT/received_events',
  type: 'User',
  site_admin: false,
  name: 'Andre Rodrigues Melgaço dos Santos',
  company: null,
  blog: 'https://www.linkedin.com/in/andr%C3%A9-rodrigues-86369544/',
  location: 'Várzea Grande,MT,Brazil',
  email: null,
  hireable: true,
  bio: 'Front End Developer',
  twitter_username: null,
  public_repos: 40,
  public_gists: 0,
  followers: 2,
  following: 4,
  created_at: '2019-09-02T18:26:16Z',
  updated_at: '2022-01-06T13:35:01Z',
};
