export default [
  {
    login: 'kvnol',
    id: 3299130,
    node_id: 'MDQ6VXNlcjMyOTkxMzA=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3299130?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/kvnol',
    html_url: 'https://github.com/kvnol',
    followers_url: 'https://api.github.com/users/kvnol/followers',
    following_url: 'https://api.github.com/users/kvnol/following{/other_user}',
    gists_url: 'https://api.github.com/users/kvnol/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/kvnol/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/kvnol/subscriptions',
    organizations_url: 'https://api.github.com/users/kvnol/orgs',
    repos_url: 'https://api.github.com/users/kvnol/repos',
    events_url: 'https://api.github.com/users/kvnol/events{/privacy}',
    received_events_url: 'https://api.github.com/users/kvnol/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'RodrigoErico',
    id: 54871018,
    node_id: 'MDQ6VXNlcjU0ODcxMDE4',
    avatar_url: 'https://avatars.githubusercontent.com/u/54871018?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/RodrigoErico',
    html_url: 'https://github.com/RodrigoErico',
    followers_url: 'https://api.github.com/users/RodrigoErico/followers',
    following_url:
      'https://api.github.com/users/RodrigoErico/following{/other_user}',
    gists_url: 'https://api.github.com/users/RodrigoErico/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/RodrigoErico/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/RodrigoErico/subscriptions',
    organizations_url: 'https://api.github.com/users/RodrigoErico/orgs',
    repos_url: 'https://api.github.com/users/RodrigoErico/repos',
    events_url: 'https://api.github.com/users/RodrigoErico/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/RodrigoErico/received_events',
    type: 'User',
    site_admin: false,
  },
];
